apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            # Kafka bağlantısı
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            # Mongo bağlantısı (username & password dahil)
            - name: MONGO_URI
              value: "mongodb://root:rootpassword@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}"



