image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 88066445baa3fd83e645de30216b913794c7e7e2

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

