image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: ad7f55982b6c17e8e796532b140a69116ec0122f

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

