image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: d55e7254e75e1de4e66d4dcb7cfc7f2a57cf8fe3

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

