image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 1a5d720ab48fa50a94cbe36932fb4d352dd03a54

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

