image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: d9768f6b9ae08e0b62b13c3163eec8453a6c7ba5

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka.dev.svc.cluster.local   # ClusterIP servisi kullanıyoruz
  port: 9092                          # 9092 portu
  auth:
    enabled: false                    # SASL dev/test için kapalı
    clientProtocol: plaintext
    interBrokerProtocol: plaintext

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017
  username: root
  password: rootpassword
