image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: dbee04cf88dc69c371757e4bbc7d3007f06c359d

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

