image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 972c112747ba5efe1ffb02fb74a4817a0715c6f7

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

