image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 722a59fe2aea0f1643314cd3a3181393a6d329a0

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller-headless.dev.svc.cluster.local
  port: 9092
  auth:
    enabled: false          # SASL dev/test için kapalı
    clientProtocol: plaintext
    interBrokerProtocol: plaintext

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017
  username: root
  password: rootpassword
