image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: fc6bd37a9d7429d18c2e2fce13f45c7af950da14

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

