image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 7588d8122f047350c56cc66fb0c5982b22fab546

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

