image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 4a83c69be8217c157c34a6a949129a31f1c6502b

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

