image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 6740e0a0148fe1dd5656166b412c0b54aef68bba

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

