image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 406dc81dd525595cbdb824b2e53ea3f102a1746a

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

