image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: a9dc3a3e8d1af071656c6606f303837a957df2bd

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

