image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: a76b216f4c3e83aa187de4e67387062c7c9f38d0

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

