image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: e4eff6f7a2445f7b96a052bc5a4aa5cea9dd80d8

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

