image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: dd79ca717802c0882166b6fe06f065091437644b

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

