image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: a0577d11754f981444e15a92491406dd040fdac1

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka.dev.svc.cluster.local
  port: 9092
  auth:
    enabled: false

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017
  username: root
  password: rootpassword
