image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 8b40aa17d9a0b9195e451de65e8c5fee8704c0a4

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local  
  port: 9092
  auth:
    enabled: false

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017
  username: root
  password: rootpassword
