image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 634e85da3e46ee93c696720db623ad7ee767c66a

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

