image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: 5e4e858759bfa737342ff838ca59db33ed73da90

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local
  port: 9092

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017

