image:
  repository: docker.io/dsengun/kafka-mongo-app
  tag: d9768f6b9ae08e0b62b13c3163eec8453a6c7ba5

service:
  type: ClusterIP
  port: 80

kafka:
  host: kafka-controller.dev.svc.cluster.local  
  port: 9092
  auth:
    enabled: false

mongodb:
  host: mongodb.dev.svc.cluster.local
  port: 27017
  username: root
  password: rootpassword
