name: CI - Build & Push Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE=docker.io/dsengun/kafka-mongo-app:${{ github.sha }}
          echo "📦 Building $IMAGE"
          docker build -t $IMAGE ./app
          docker push $IMAGE

      - name: Update Helm values.yaml with new tag
        run: |
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" chart/kafka-mongo-app/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add chart/kafka-mongo-app/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/durul55/kafka-mongo-app-devops.git HEAD:main

